// react-test/src/App.js
import Heading from './Heading.js';
import Button from './Button.js';
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);
  const [color, setColor] = useState('#000000');
  const colors = ['#00ff00', '#ff0000', '#0000ff'];

  let handleClick = () => {
    setCount(count+1);
    setColor(colors[Math.floor(Math.random() * 3)]);
  }  

  return (
    <main>
      <Heading count={count} />     
      <Button color={color} handleClick={handleClick} />
    </main>
  )  
}

export default App;

// svelte-test/src/App.svelte
<script>
	import Button from './Button.svelte';
	import Heading from './Heading.svelte';
	let count = 0;
	let color = '#000000';

	const colors = ['#00ff00', '#ff0000', '#0000ff'];

	let handleClick = () => {
		count++;
		color = colors[Math.floor(Math.random() * 3)];
	}
</script>

<main>
	<Heading count={count} />
	<Button color={color} handleClick={handleClick} />
</main>
